// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6d9SNU4zwZMiJcV_ER_JNx2lmOsx4vWc',
    appId: '1:417912915872:web:7e9665a2fa0b2beb7c86c5',
    messagingSenderId: '417912915872',
    projectId: 'zen-mart-pro-50ab1',
    authDomain: 'zen-mart-pro-50ab1.firebaseapp.com',
    storageBucket: 'zen-mart-pro-50ab1.firebasestorage.app',
    measurementId: 'G-PQ009QP2NP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLjNjD-EGoQLe5fxIHH-Khr9ODbrdtKTk',
    appId: '1:417912915872:android:70615ff1568aa6dc7c86c5',
    messagingSenderId: '417912915872',
    projectId: 'zen-mart-pro-50ab1',
    storageBucket: 'zen-mart-pro-50ab1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtTYr1MB3b5jIuRmmqGA-0ELs0yGBfbks',
    appId: '1:417912915872:ios:780390249269086c7c86c5',
    messagingSenderId: '417912915872',
    projectId: 'zen-mart-pro-50ab1',
    storageBucket: 'zen-mart-pro-50ab1.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtTYr1MB3b5jIuRmmqGA-0ELs0yGBfbks',
    appId: '1:417912915872:ios:780390249269086c7c86c5',
    messagingSenderId: '417912915872',
    projectId: 'zen-mart-pro-50ab1',
    storageBucket: 'zen-mart-pro-50ab1.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6d9SNU4zwZMiJcV_ER_JNx2lmOsx4vWc',
    appId: '1:417912915872:web:80e154c3a86b696c7c86c5',
    messagingSenderId: '417912915872',
    projectId: 'zen-mart-pro-50ab1',
    authDomain: 'zen-mart-pro-50ab1.firebaseapp.com',
    storageBucket: 'zen-mart-pro-50ab1.firebasestorage.app',
    measurementId: 'G-XSGK5FGN66',
  );
}
